[config]
schemaVersion = "0.0.2"

[package]
namespace = "Atopy"
name = "QuickPing"
versionNumber = "1.4.3"
description = "Ping what you see, with colors !"
websiteUrl = "https://github.com/Vodianoi/QuickPingMod"
containsNsfwContent = false
dependencies = {  }

[build]
icon = "Package/icon.png"
readme = "Package/README.md"
outdir = "./build"

[[build.copy]]
source = "./Package/plugins/QuickPing.dll"
target = "./QuickPing.dll"

[publish]
repository = "https://thunderstore.io"
communities = [ "Valheim", ]
categories = [ "client-side", "tweaks", "utility", "misc", "tools", "mods" ]
