name: "Release"

on:
  pull_request:
    branches: 
      - 'master'   
    types: 
      - closed


jobs:
        
  build: 
    name: "Build and Deploy"  
    if: github.event.pull_request.merged == true
    runs-on: windows-latest 
    steps:
      # CHECKOUT
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      # Setups
      ##############
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
      ##############
        
      # Add bepinex package source
      - name: Add source
        run: |
            dotnet nuget add source "https://nuget.bepinex.dev/v3/index.json" --name baget 

      # Useless?
      - name: Navigate to Workspace
        run: cd $GITHUB_WORKSPACE

      - name: Restore Packages
        run: nuget restore QuickPing.sln

      - name: Build Solution
        run: |
          msbuild.exe QuickPing.sln /p:platform="Any CPU" /p:configuration="Release"
          
          
      - uses: ncipollo/release-action@v1
        with:
          artifacts: QuickPing/QuickPing.zip
          generateReleaseNotes: true
          # bodyFile: QuickPing/Package/CHANGELOG.md
          commit: ${{ github.event.pull_request.head.sha }}
          tag: ${{ env.GitVersion_MajorMinorPatch }}
          updateOnlyUnreleased: true
          name: "Release: ${{ env.GitVersion_SemVer }}"
          draft: true



