name: Publish Thunder Mod

# Run when a new release is... released
on: 
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # Use checkout to publish the files in your repo
      - uses: ciiiii/toml-editor@1.0.0
        with:
            file: "QuickPing/thunderstore.toml"
            key: "package.versionNumber"
            value: ${{ github.ref_name }}
      - run: |
         ls
         wget https://github.com/thunderstore-io/thunderstore-cli/releases/download/0.1.6/tcli-0.1.6-linux-x64.tar.gz
         tar -xf tcli-0.1.6-linux-x64.tar.gz
         mv ./tcli-0.1.6-linux-x64/tcli QuickPing/tcli
         cd QuickPing
         ./tcli publish --token ${{ secrets.THUNDERSTORE_TOKEN }}
