name: "Upload to Thunderstore and NexusMods"

on:
  release:
    types: [published]
    
jobs:
  publish-modpackage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: download-release-asset
        name: Download release asset
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: tags/${GITHUB_REF}
          file: QuickPing.zip
          target: QuickPing.zip
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: Vodianoi/uploadMod@0.9.40
        with:
          mod-id: '2033' #Nexus
          archive-file: QuickPing.zip
          file-name: 'QuickPing'
          version: $GITHUB_REF
          category: 'Main'
          description: "Ping what you see and pin it on the map !"
          game: valheim
          namespace: 'com.atopy.plugins.quickping'
          tomlConfigPath: 'QuickPing/thunderstore.toml'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NEXUSMOD_API_KEY: ${{ secrets.NEXUSMOD_API_KEY }}
          NEXUSMOD_COOKIE_NEXUSID: ${{ secrets.NEXUSMOD_COOKIE_NEXUSID }}
          NEXUSMOD_COOKIE_SID_DEVELOP: ${{ secrets.NEXUSMOD_COOKIE_SID_DEVELOP }}
          THUNDERSTORE_TOKEN: ${{ secrets.THUNDERSTORE_TOKEN }}
