name: "Upload to Thunderstore and NexusMods"

on:
  release:
    types: [published]
    
jobs:
  publish-modpackage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: robinraju/release-downloader@v1.7
        with:
          tag: "${{ github.ref_name }}"
          fileName: "QuickPing.zip"
      - uses: Vodianoi/uploadMod@0.9.41
        with:
          mod-id: '2033' #Nexus
          archive-file: QuickPing.zip
          file-name: 'QuickPing'
          version: "${{ github.ref_name }}"
          category: 'Main'
          description: Ping what you see and pin it on the map !
          game: valheim
          namespace: 'com.atopy.plugins.quickping'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NEXUSMOD_API_KEY: ${{ secrets.NEXUSMOD_API_KEY }}
          NEXUSMOD_COOKIE_NEXUSID: ${{ secrets.NEXUSMOD_COOKIE_NEXUSID }}
          NEXUSMOD_COOKIE_SID_DEVELOP: ${{ secrets.NEXUSMOD_COOKIE_SID_DEVELOP }}
          
      - uses: GreenTF/upload-thunderstore-package@v3
        with:
          namespace: Atopy # the thunderstore 'team' to publish under
          description: Ping what you see and pin it on the map ! 
          token: ${{ secrets.THUNDERSTORE_TOKEN }}
          name: QuickPing # the name of the package
          version: ${{ github.ref_name }} # Use the tag as the package version
          community: Valheim
          file: QuickPing.zip
